export const DRUGS = [
  {
    id: 'pevarojet',
    dbId: 'eze_pita',
    name: '페바로젯',
    ingredient: ['ezetimibe', 'pitavastatin'],
    excludeIngredient: ['fenofibrate', 'fenofibric'],
    myVendor: '안국약품',
    metric: 'qty',
    topN: 5,
    showGR: true,
    showDonut: true,
    // 데이터 확인법: 로우데이터 성분 컬럼에서 ezetimibe+pitavastatin AND 조건 필터, fenofibrate/fenofibric 제외, 판매사 기준 집계
  },
  {
    id: 'levo_tension',
    dbId: 'levo_tension',
    name: '레보텐션',
    ingredient: ['amlodipine'],
    excludeIngredient: ['valsartan', 'olmesartan', 'losartan', 'telmisartan', 'irbesartan', 'candesartan', 'fimasartan'],
    myVendor: '안국약품',
    metric: 'qty',
    topN: 5,
    showGR: true,
    showDonut: true,
    // 데이터 확인법: 백데이터 탭 [레보텐션backdata], 제조사 컬럼 기준 집계, 처방량(qty) 사용
  },
  {
    id: 'levo_saltan',
    dbId: 'levo_saltan',
    name: '레보살탄',
    ingredient: ['amlodipine', 'valsartan'],
    excludeIngredient: [],
    myVendor: '안국약품',
    metric: 'qty',
    topN: 5,
    showGR: true,
    showDonut: true,
    // 데이터 확인법: 백데이터 탭 [레보살탄backdata], 제조사 컬럼 기준 집계, 처방량(qty) 사용
  },
  {
    id: 'sinectura',
    dbId: 'sinectura',
    name: '시네츄라',
    ingredient: ['levodropropizine'],
    excludeIngredient: [],
    myVendor: '안국약품',
    // 처방건수(rx) 사용 — 8대품목 중 유일하게 처방건수 기준 집계 (나머지는 처방량 qty)
    metric: 'rx',
    topN: 5,
    showGR: true,
    showDonut: true,
    // 데이터 확인법: 미확인 — 확인 후 업데이트 필요
  },
  {
    id: 'rupafin',
    dbId: 'rupafin',
    name: '루파핀',
    ingredient: ['rupatadine'],
    excludeIngredient: [],
    excludeDosage: ['(SY)', '(LQ)', '(IJ)'],  // 시럽/액제/주사 제외, 정제 계열만
    myVendor: '안국약품',
    metric: 'qty',
    topN: 5,
    showGR: true,
    showDonut: true,
  },
  {
    id: 'anycof',
    dbId: 'anycof',
    name: '애니코프',
    ingredient: ['levodropropizine'],
    excludeIngredient: [],
    excludeDosage: ['(SY)', '(LQ)', '(IJ)', '(SS)'],
    marketProduct: '칼로민',  // 시장 파일 감지용 — 이 제품명이 있으면 anycof 시장 파일로 인식
    myVendor: '안국약품',
    metric: 'qty',
    topN: 5,
    showGR: true,
    showDonut: true,
  },
  {
    id: 'retopra',
    dbId: 'retopra',
    name: '레토프라',
    ingredient: ['s-pantoprazole'],
    excludeIngredient: [],
    myVendor: '안국약품',
    metric: 'qty',
    topN: 5,
    showGR: true,
    showDonut: true,
    // 데이터 확인법: 미확인 — 확인 후 업데이트 필요
  },
  {
    id: 'polax',
    dbId: 'polax',
    name: '폴락스',
    ingredient: ['macrogol'],
    excludeIngredient: [],
    myVendor: '안국약품',
    metric: 'qty',
    topN: 5,
    showGR: true,
    showDonut: true,
    marketByBrand: true,
    brandMerges: {
      '마그밀에스':  '마그밀',
      '듀락칸 이지': '듀락칸',
      '둘코락스 에스': '둘코락스',
    },
    // 특정 ATC 카테고리 내에서 허용할 브랜드 지정 (미지정 ATC는 전체 허용)
    atcBrandWhitelist: {
      '[A2A1] 단일제산제': ['마그밀'],
    },
  },
];
